# Generated by Django 3.0.3 on 2020-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200204_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=2000),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
